#!/usr/bin/env bash
#
# status.sh — regenerate the block between the two status markers in README.md.
#
# Every number here is derived from git or from counting files. Nothing in this
# script is hand-maintained, and nothing it writes should ever be edited by
# hand: a generated block that someone has corrected is a block that will be
# wrong again on the next run, silently.
#
# What this deliberately does not do: read docs/ROADMAP.md, parse the capability
# ladder, or write to any file other than README.md and the badge JSON at
# docs/harness-badge.json. The ladder is prose, drawn
# by hand and maintained by hand, and a shell script that lifts ASCII art out of
# one markdown file and injects it into another breaks the first time someone
# adds a blank line — and breaks silently, which is the failure this repository
# exists to make impossible.
#
# `-uo pipefail`, deliberately not `-e`: `git describe --tags` exits non-zero in
# a repository with no tags, and this repository has none. Every git command
# that can legitimately fail carries its own fallback.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || {
    printf 'status: cannot reach the repository root\n' >&2
    exit 2
}

README=README.md
BEGIN='<!-- status:begin -->'
END='<!-- status:end -->'

[ -f "$README" ] || {
    printf 'status: %s not found\n' "$README" >&2
    exit 2
}
grep -qF "$BEGIN" "$README" || {
    printf 'status: %s has no begin marker\n' "$README" >&2
    exit 2
}
grep -qF "$END" "$README" || {
    printf 'status: %s has no end marker\n' "$README" >&2
    exit 2
}

version="$(git describe --tags 2>/dev/null)"
[ -n "$version" ] || version='no tag yet'

commits="$(git rev-list --count HEAD 2>/dev/null)"
[ -n "$commits" ] || commits='0'

last="$(git log -1 --format=%cs 2>/dev/null)"
[ -n "$last" ] || last='no commits yet'

# Counted from the tree. `teeth plant cases` rather than `teeth cases`, because
# teeth.sh also runs a contract case that is a code path and not a file — nine
# cases exist and eight are files. Reporting nine would mean adding one by hand
# inside a generated block, which is the thing this script is for avoiding.
gates="$(find scripts/gates -maxdepth 1 -name 'gate-*.sh' 2>/dev/null | wc -l | tr -d ' ')"
plants="$(find scripts/gates/teeth -maxdepth 1 -name 'plant-*.sh' 2>/dev/null | wc -l | tr -d ' ')"
units="$(find docs/prompts -maxdepth 1 -name '[0-9]*.md' 2>/dev/null | wc -l | tr -d ' ')"

# One span row per filed driving-unit record. The endpoints and the count
# are of commits touching that record file — not the unit's whole work,
# which no derivation can recover from git alone — and the row says so.
# `tail -1` rather than `--reverse | head -1`, because head closing the
# pipe early would hand git a SIGPIPE under pipefail. An uncommitted
# record file has no span yet and the row says that instead of a range.
unit_rows="$(
    for p in docs/prompts/[0-9]*.md; do
        [ -f "$p" ] || continue
        nn="$(basename "$p" | cut -c1-2)"
        u_last="$(git rev-list --abbrev-commit -1 HEAD -- "$p" 2>/dev/null)"
        if [ -n "$u_last" ]; then
            u_first="$(git rev-list --abbrev-commit HEAD -- "$p" 2>/dev/null | tail -1)"
            u_count="$(git rev-list --count HEAD -- "$p" 2>/dev/null)"
            u_word=commits
            [ "$u_count" = 1 ] && u_word=commit
            printf '| unit %s record span | %s..%s, %s %s touch%s it |\n' \
                "$nn" "$u_first" "$u_last" "$u_count" "$u_word" \
                "$([ "$u_count" = 1 ] && printf 'es')"
        else
            printf '| unit %s record span | file not committed yet |\n' "$nn"
        fi
    done
)"

block="$(
    printf '| | |\n'
    printf '|---|---|\n'
    printf '| version | %s |\n' "$version"
    printf '| commits | %s |\n' "$commits"
    printf '| last commit | %s |\n' "$last"
    printf '| gates | %s |\n' "$gates"
    printf '| teeth plant cases | %s |\n' "$plants"
    printf '| unit records filed | %s |\n' "$units"
    [ -z "$unit_rows" ] || printf '%s\n' "$unit_rows"
    printf '\n'
    printf 'A record span counts commits touching that file, not the unit'"'"'s\n'
    printf 'whole work. The block is generated before the commit that carries\n'
    printf 'it and describes that commit'"'"'s parent. Generated by\n'
    printf '`scripts/status.sh`. Do not edit between the markers.\n'
)"

tmp="$(mktemp "${TMPDIR:-/tmp}/status.XXXXXX")" || {
    printf 'status: could not create a temporary file\n' >&2
    exit 2
}
blockfile="$(mktemp "${TMPDIR:-/tmp}/status-block.XXXXXX")" || {
    printf 'status: could not create a temporary file\n' >&2
    exit 2
}
trap 'rm -f "$tmp" "$blockfile"' EXIT

printf '%s\n' "$block" > "$blockfile"

# The block is handed to awk through a file rather than through -v. An awk
# variable assignment cannot carry embedded newlines: `-v block="$block"` fails
# with `newline in string` and the block is never inserted. Found by running it.
#
# Both temporary files live outside the repository on purpose, so that a run of
# this script leaves README.md as the only path it touched.
awk -v bf="$blockfile" -v b="$BEGIN" -v e="$END" '
    $0 == b {
        print
        while ((getline line < bf) > 0) print line
        close(bf)
        inside = 1
        next
    }
    $0 == e { inside = 0; print; next }
    inside { next }
    { print }
' "$README" > "$tmp" || {
    printf 'status: could not rewrite %s\n' "$README" >&2
    exit 2
}

cat "$tmp" > "$README" || {
    printf 'status: could not write %s\n' "$README" >&2
    exit 2
}

# The shields endpoint JSON, committed as a generated artifact under the same
# one-behind convention as the block above. All three figures are derived —
# one source of truth, zero typed numbers. The contract-case count is of
# argument-less `run_contract_case` call lines in teeth.sh: the `$` anchor is
# load-bearing, because without it the pattern also matches the function
# definition line and reads 2 against a true 1, measured. The message keeps
# the plant/contract split the 2026-08-01 finding demanded rather than a sum
# that hides the code-path case. No color field: shields' default grey claims
# nothing, and these are counts, not verdicts.
contracts="$(grep -c '^run_contract_case$' scripts/gates/teeth.sh)"
BADGE=docs/harness-badge.json
printf '{\n  "schemaVersion": 1,\n  "label": "harness",\n  "message": "gates %s / teeth %s+%s"\n}\n' \
    "$gates" "$plants" "$contracts" > "$BADGE" || {
    printf 'status: could not write %s\n' "$BADGE" >&2
    exit 2
}

printf 'status: %s regenerated (%s commits, %s gates, %s plant cases, %s records), %s written\n' \
    "$README" "$commits" "$gates" "$plants" "$units" "$BADGE" >&2
